// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsCore.Models
{
    [Table("New_agreementExtensionBase")]
    public partial class NewAgreementExtensionBase
    {
        [Key]
        [Column("New_agreementId")]
        public Guid NewAgreementId { get; set; }
        [Column("New_name")]
        [StringLength(100)]
        public string NewName { get; set; }
        [Column("New_number")]
        public int? NewNumber { get; set; }
        [Column("New_isback")]
        public bool? NewIsback { get; set; }
        [Column("New_inbuh")]
        public bool? NewInbuh { get; set; }
        [Column("New_isfree")]
        public bool? NewIsfree { get; set; }
        [Column("New_agreement")]
        public Guid? NewAgreement { get; set; }
        [Column("New_date", TypeName = "datetime")]
        public DateTime? NewDate { get; set; }
        [Column("New_executor")]
        public int? NewExecutor { get; set; }
        [Column("New_bp_agreement")]
        public Guid? NewBpAgreement { get; set; }
        [Column("New_litera")]
        [StringLength(15)]
        public string NewLitera { get; set; }
        [Column("New_subtype")]
        public int? NewSubtype { get; set; }
        [Column("New_dogovor_type_agreement")]
        public Guid? NewDogovorTypeAgreement { get; set; }
        [Column("New_executor_agreement")]
        public Guid? NewExecutorAgreement { get; set; }
        [Column("New_Code")]
        [StringLength(100)]
        public string NewCode { get; set; }
        [Column("New_delete_date", TypeName = "datetime")]
        public DateTime? NewDeleteDate { get; set; }
        [Column("New_why_delete_contract")]
        public string NewWhyDeleteContract { get; set; }
        [Column("New_button")]
        [StringLength(100)]
        public string NewButton { get; set; }
        [Column("New_for")]
        public int? NewFor { get; set; }
        [Column("New_CrmCode")]
        [StringLength(100)]
        public string NewCrmCode { get; set; }
        [Column("New_deal_date", TypeName = "datetime")]
        public DateTime? NewDealDate { get; set; }
        [Column("New_end_date", TypeName = "datetime")]
        public DateTime? NewEndDate { get; set; }
        [Column("New_abonent_cost", TypeName = "decimal(23, 10)")]
        public decimal? NewAbonentCost { get; set; }
        [Column("New_is_export_to_1C")]
        public bool? NewIsExportTo1c { get; set; }
        [Column("New_service_1c")]
        public Guid? NewService1c { get; set; }
        [Column("New_check_number")]
        [StringLength(100)]
        public string NewCheckNumber { get; set; }
        [Column("New_take_free_number")]
        [StringLength(100)]
        public string NewTakeFreeNumber { get; set; }
        [Column("New_must_delete")]
        public bool? NewMustDelete { get; set; }
        [Column("New_summ_teh", TypeName = "money")]
        public decimal? NewSummTeh { get; set; }
        [Column("new_summ_teh_Base", TypeName = "money")]
        public decimal? NewSummTehBase { get; set; }
        [Column("New_arenda_teh", TypeName = "money")]
        public decimal? NewArendaTeh { get; set; }
        [Column("new_arenda_teh_Base", TypeName = "money")]
        public decimal? NewArendaTehBase { get; set; }
        [Column("New_vzaim_teh", TypeName = "money")]
        public decimal? NewVzaimTeh { get; set; }
        [Column("new_vzaim_teh_Base", TypeName = "money")]
        public decimal? NewVzaimTehBase { get; set; }
        [Column("New_cash_date", TypeName = "datetime")]
        public DateTime? NewCashDate { get; set; }
        [Column("New_work_type")]
        [StringLength(100)]
        public string NewWorkType { get; set; }
        [Column("New_comment")]
        public string NewComment { get; set; }
        [Column("New_action_date", TypeName = "datetime")]
        public DateTime? NewActionDate { get; set; }
        [Column("New_change_button")]
        [StringLength(100)]
        public string NewChangeButton { get; set; }
        [Column("New_export_to_1c")]
        public bool? NewExportTo1c { get; set; }
        [Column("New_nds_up")]
        public bool? NewNdsUp { get; set; }
        [Column("New_button_beta")]
        [StringLength(100)]
        public string NewButtonBeta { get; set; }
        [Column("New_beta")]
        [StringLength(100)]
        public string NewBeta { get; set; }
        [Column("New_history_button")]
        [StringLength(100)]
        public string NewHistoryButton { get; set; }
        [Column("New_btn_Union")]
        [StringLength(100)]
        public string NewBtnUnion { get; set; }

        [ForeignKey(nameof(NewAgreementId))]
        [InverseProperty(nameof(NewAgreementBase.NewAgreementExtensionBase))]
        public virtual NewAgreementBase NewAgreement1 { get; set; }
        [ForeignKey(nameof(NewAgreement))]
        [InverseProperty(nameof(NewGuardObjectBase.NewAgreementExtensionBase))]
        public virtual NewGuardObjectBase NewAgreementNavigation { get; set; }
        [ForeignKey(nameof(NewBpAgreement))]
        [InverseProperty(nameof(AccountBase.NewAgreementExtensionBase))]
        public virtual AccountBase NewBpAgreementNavigation { get; set; }
        [ForeignKey(nameof(NewDogovorTypeAgreement))]
        [InverseProperty(nameof(NewDogovorTypeBase.NewAgreementExtensionBase))]
        public virtual NewDogovorTypeBase NewDogovorTypeAgreementNavigation { get; set; }
    }
}