// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsCore.Models
{
    [Table("New_dogovor_typeExtensionBase")]
    public partial class NewDogovorTypeExtensionBase
    {
        [Key]
        [Column("New_dogovor_typeId")]
        public Guid NewDogovorTypeId { get; set; }
        [Column("New_name")]
        [StringLength(100)]
        public string NewName { get; set; }
        [Column("New_CrmCode")]
        [StringLength(100)]
        public string NewCrmCode { get; set; }
        [Column("New_service_name_1C")]
        [StringLength(100)]
        public string NewServiceName1c { get; set; }
        [Column("New_vision")]
        public int? NewVision { get; set; }
        [Column("New_dogovor_type_1C")]
        [StringLength(100)]
        public string NewDogovorType1c { get; set; }
        [Column("New_techService")]
        public bool? NewTechService { get; set; }

        [ForeignKey(nameof(NewDogovorTypeId))]
        [InverseProperty(nameof(NewDogovorTypeBase.NewDogovorTypeExtensionBase))]
        public virtual NewDogovorTypeBase NewDogovorType { get; set; }
    }
}