// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsCore.Models
{
    [Table("new_new_agreement_new_guard_objectBase")]
    public partial class NewNewAgreementNewGuardObjectBase
    {
        [Key]
        [Column("new_new_agreement_new_guard_objectId")]
        public Guid NewNewAgreementNewGuardObjectId { get; set; }
        public byte[] VersionNumber { get; set; }
        [Column("new_agreementid")]
        public Guid NewAgreementid { get; set; }
        [Column("new_guard_objectid")]
        public Guid NewGuardObjectid { get; set; }

        [ForeignKey(nameof(NewAgreementid))]
        [InverseProperty(nameof(NewAgreementBase.NewNewAgreementNewGuardObjectBase))]
        public virtual NewAgreementBase NewAgreement { get; set; }
        [ForeignKey(nameof(NewGuardObjectid))]
        [InverseProperty(nameof(NewGuardObjectBase.NewNewAgreementNewGuardObjectBase))]
        public virtual NewGuardObjectBase NewGuardObject { get; set; }
    }
}