// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReportsCore.Models
{
    public partial class SystemUserExtensionBase
    {
        [Key]
        public Guid SystemUserId { get; set; }
        [Column("New_password")]
        [StringLength(100)]
        public string NewPassword { get; set; }
        [Column("New_is_curator")]
        public bool? NewIsCurator { get; set; }
        [Column("New_is_headmounter")]
        public bool? NewIsHeadmounter { get; set; }
        [Column("New_tel_number_auth")]
        [StringLength(11)]
        public string NewTelNumberAuth { get; set; }
    }
}